plugins {
    id 'java-library'
    id 'maven-publish'
}
group = 'pvz'
version = '0.1.0'
ext { gdxVersion = '1.12.1' }
repositories {
    maven { url 'https://maven.myket.ir' }
    mavenCentral()
    maven { url 'https://jitpack.io' }
}
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
dependencies {
    api "com.badlogicgames.gdx:gdx:${gdxVersion}"
}
